server:
  port: 8080
  servlet:
    context-path: "/mais-consulta"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

spring:
  datasource:
    url: jdbc:sqlserver://maisconsultadb.database.windows.net:1433;database=maisconsultadb;encrypt=true;trustServerCertificate=false;sendTimeAsDateTime=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: "mais-consulta@maisconsultadb"
    password: "#Grupo02"

  jpa:
#    show-sql: true
#    format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
