server:
  port: 8080
  servlet:
    context-path: "/mais-consulta"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

database:
  schema: maisconsulta
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: ${DB_URL:jdbc:sqlserver://grupo02.database.windows.net:1433}
  username: ${DB_USERNAME:Grupo02@grupo02}
  password: ${DB_PASSWORDS:IXzGiRLOa%!6kqfYdsYBskbEu2d0%WQ9J4wxdZkcH9KBHOZJqz}
