server:
  port: 8080
  servlet:
    context-path: "/mais-consulta"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

spring:
  datasource:
    url: jdbc:h2:mem:bandtec
  jpa:
    properties.hibernate.format_sql: TRUE
    show-sql: TRUE

database:
  schema: maisconsulta
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: ${DB_URL:jdbc:sqlserver://grupo02.database.windows.net:1433}
  username: ${DB_USERNAME:Grupo02@grupo02}
  password: ${DB_PASSWORDS:IXzGiRLOa%!6kqfYdsYBskbEu2d0%WQ9J4wxdZkcH9KBHOZJqz}
