name: Heroku Deployment

on:
  push:
    branches: [ main ]

jobs:
  production-deploy:
      if: github.repository == 'octo-org/octo-repo-prod'
      runs-on: ubuntu-latest
  
  build:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP}}
