name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-format:
    runs-on: ubuntu-latest
    name: Verify Source Format
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.x
      - name: Verify Format and License
        run: mvn spotless:check
  build:
    name: Java ${{ matrix.java }} Maven Test on ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8.0.x, 11.0.x, 17.0.x ]
        os: [ windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('pom.xml', '**/pom.xml') }}
      - name: Build with Maven
        run: |
          mvn clean test -q -B --define=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn